### ISSUE TITLE
Accented characters

### ISSUE THREAD

**Issue by johenrik** [GravitonDigital/app-azure-ad-idprovider#1]
We have an issue with a user that has the name André. The AzureAD provider fails with:
`UUID format incorrect: user:azuread:andré`
in
`
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:141)
	at com.enonic.xp.node.UUID.<init>(UUID.java:27)
	at com.enonic.xp.node.NodeId.<init>(NodeId.java:21)
	at com.enonic.xp.node.NodeId.from(NodeId.java:42)
	at com.enonic.xp.core.impl.security.PrincipalNodeTranslator.toCreateNodeParams(PrincipalNodeTranslator.java:94)
	at com.enonic.xp.core.impl.security.SecurityServiceImpl.doCreateUser(SecurityServiceImpl.java:650)
	at com.enonic.xp.core.impl.security.SecurityServiceImpl.createUser(SecurityServiceImpl.java:685)
	at com.enonic.xp.lib.auth.CreateUserHandler.createUser(CreateUserHandler.java:49)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1471$5707A$auth.L:1#createUser(com.gravitondigital.app.azureadidprovider:/lib/xp/auth.js:206)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1470$3478$user.L:1#createOrModify#L:97(com.gravitondigital.app.azureadidprovider:/lib/azure-ad-id-provider/auth/user.js:98)
`
It seems like names needs to be sanitized before set as UUID.

**Comment by Garlov** [comment]
Ah, that's good to know. Shouldn't be too big of a fix. I'll take a look this weekend. Sorry for the delay
